$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  rust:
  - 'src/**/*.rs'
  - 'src/**/*.toml'
  - 'src/**/*.yml'

tasks:
  install:
    command: 'cargo install --path .'
    inputs:
    - '@globs(rust)'
    options:
      mergeDeps: append

  dev:
    command: 'cargo run'
    inputs:
    - '@globs(rust)'
    options:
      mergeDeps: append
      cache: false

  build:
    command: 'cargo build'
    inputs:
    - '@globs(rust)'
    options:
      runInCI: true

  test:
    command: 'cargo test'
    inputs:
    - '@globs(rust)'
    options:
      runInCI: true
      
