$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  typescript:
  - 'src/**/*.ts'
  - 'src/**/*.tsx'
  - 'src/**/*.js'
  - 'src/**/*.jsx'
  - 'tests/**/*.ts'
  - 'tests/**/*.tsx'
  - 'tests/**/*.js'
  - 'tests/**/*.jsx'
  - 'prisma/**/*.prisma'
  configs:
  - 'tsconfig.json'
  - 'tsconfig.*.json'
  - 'vite.config.ts'
  - 'prisma/**/*.prisma'
  - 'prisma/**/*.yml'
  - 'bun.config.ts'
  assets:
  - 'public/**/*'
tasks:
  install:
    command: 'bun install'
    inputs:
    - '@globs(typescript)'
    - '@globs(configs)'
    options:
      mergeDeps: append

  dev:
    command: 'bun run dev'
    inputs:
    - '@globs(typescript)'
    - '@globs(configs)'
    options:
      mergeDeps: append     



  preview:
    command: 'bun run preview'
    inputs:
    - '@globs(typescript)'
    - '@globs(assets)'
    options:
      runInCI: true

  test:
    command: 'bun test'
    inputs:
    - '@globs(typescript)'
    options:
      runInCI: true

  typecheck:
    command: 'bun run tsc'
    inputs:
    - '@globs(typescript)'
    - '@globs(configs)'
    options:
      runInCI: true

  lint:
    command: 'bun run eslint'
    inputs:
    - '@globs(typescript)'
    options:
      runInCI: true

  format:
    command: 'bun run prettier'
    inputs:
    - '@globs(typescript)'
    options:
      runInCI: true
